// 日本語対応PDF生成ユーティリティ
export class JapanesePDF {
  private static NotoSansCJP = `// Japanese font (Noto Sans CJK JP) - using built-in fallback
  // This is a placeholder for font loading logic
  // In production, you would load an actual Japanese font`

  static create() {
    // ワークアラウンド：Canvasを使って文字を画像に変換
    return {
      addText: (
        doc: { setFontSize: (size: number) => void; text: (text: string, x: number, y: number, options?: { align?: string }) => void },
        text: string,
        x: number,
        y: number,
        options?: { align?: string; fontSize?: number }
      ) => {
        // 日本語の場合は特殊処理
        if (/[\u3040-\u309F\u30A0-\u30FF\u4E00-\u9FAF]/.test(text)) {
          // 今はASCIIに変換（一時的な対応）
          const asciiText = text.replace(/[^\x20-\x7E]/g, '?')
          if (options?.fontSize) doc.setFontSize(options.fontSize)
          if (options?.align) {
            doc.text(asciiText, x, y, { align: options.align })
          } else {
            doc.text(asciiText, x, y)
          }
        } else {
          // 英語の場合は通常通り
          if (options?.fontSize) doc.setFontSize(options.fontSize)
          if (options?.align) {
            doc.text(text, x, y, { align: options.align })
          } else {
            doc.text(text, x, y)
          }
        }
      }
    }
  }
}

// 日本語変換ヘルパー
export const convertJapanese = (text: string): string => {
  // 簡易的な日本語対応（一時的）
  const replacements: { [key: string]: string } = {
    '申請番号': 'Application No.',
    '申請者情報': 'Applicant Information',
    '製品情報': 'Product Information',
    'お名前': 'Name',
    '製品名': 'Product',
    '購入日': 'Purchase Date',
    '購入店舗': 'Store',
    '申請パーツ': 'Requested Parts',
    '点': 'items',
    '画像': 'Image',
    '組立番号': 'Assembly',
    '部品名': 'Part Name',
    '数量': 'Quantity',
    '© 2024 PANZER BLOCKS. All rights reserved.': 'Copyright © 2025 Ulysseus Co., Ltd.',
    'この書類はシステムにより自動生成されました。': 'This document was automatically generated by the system.'
  }

  let result = text
  Object.entries(replacements).forEach(([jp, en]) => {
    result = result.replace(new RegExp(jp, 'g'), en)
  })

  // 残りの日本語はASCIIに変換
  return result.replace(/[^\x20-\x7E]/g, '?')
}